import Head from "next/head";
import { Encode_Sans } from "@next/font/google";
import { Flex, Heading } from "@chakra-ui/react";
import InputForm from "../components/input-form";
import Seating from "../components/seating";
import useAssignSeats from "../hooks/use-assign-seats";

const globalFont = Encode_Sans({ subsets: ["latin"] });

export default function Home() {
  const { seatsByBlock, setSeatsByBlock, setNumOfPassengers, bookedSeats, remainingPassengers } = useAssignSeats();

  return (
    <>
      <Head>
        <title>Algorithm Airplane Seating</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={globalFont.className}>
        <Heading as="h1" size="xl" marginBlock={10} color="teal.500" textAlign="center">
          Algorithm Airplane Seating
        </Heading>

        <Flex wrap="wrap" justifyContent="center" gap={5}>
          <InputForm setSeatsByBlock={setSeatsByBlock} setNumOfPassengers={setNumOfPassengers} />
          <Seating seatsByBlock={seatsByBlock} bookedSeats={bookedSeats} remainingPassengers={remainingPassengers} />
        </Flex>
      </main>
    </>
  );
}
